---
- name: Check if Cursor is installed
  ansible.builtin.stat:
    path: "{{ cursor_install_path }}"
  register: cursor_bin

- name: Download Cursor AppImage
  ansible.builtin.get_url:
    url: "{{ cursor_appimage_url }}"
    dest: "{{ cursor_install_path }}"
    mode: '0755'
  when: not cursor_bin.stat.exists
